### ISSUE TITLE
Acc is always zero?

### ISSUE THREAD

**Issue by gden138** [theidentity/Improved-GAN-PyTorch#1]
Hi, first thank you for the code.However, I encountered the following problems when running ssl_gan:

100%|██████████| 1/1 [00:04<00:00,  4.87s/it]
100%|██████████| 1/1 [00:02<00:00,  2.44s/it]Epoch 131 disc_loss 0.003 gen_loss 112.479 val_loss 48.323 acc 0.000

100%|██████████| 1/1 [00:04<00:00,  4.60s/it]
100%|██████████| 1/1 [00:02<00:00,  2.05s/it]Epoch 132 disc_loss 0.003 gen_loss 105.580 val_loss 51.352 acc 0.000

100%|██████████| 1/1 [00:04<00:00,  4.83s/it]
100%|██████████| 1/1 [00:02<00:00,  2.01s/it]Epoch 133 disc_loss 0.005 gen_loss 167.525 val_loss 53.761 **acc 0.000**

100%|██████████| 1/1 [00:05<00:00,  5.39s/it]
100%|██████████| 1/1 [00:02<00:00,  2.21s/it]
Epoch 134 disc_loss 0.007 gen_loss 161.507 val_loss 55.156 **acc 0.000**
100%|██████████| 1/1 [00:05<00:00,  5.22s/it]
100%|██████████| 1/1 [00:02<00:00,  2.53s/it]
Epoch 135 disc_loss 0.005 gen_loss 159.223 val_loss 55.300 **acc 0.000**
100%|██████████| 1/1 [00:04<00:00,  4.88s/it]
100%|██████████| 1/1 [00:01<00:00,  1.63s/it]
Epoch 136 disc_loss 0.003 gen_loss 171.475 val_loss 54.829 **acc 0.000**
100%|██████████| 1/1 [00:05<00:00,  5.41s/it]
100%|██████████| 1/1 [00:01<00:00,  1.95s/it]
Epoch 137 disc_loss 0.003 gen_loss 157.677 val_loss 53.716 **acc 0.000**
Why is acc always 0?  I have not known how to solve it, please help me, thank you very much! 
I use pytorch1.1.0 and python3.5.6. Same problem when I run sup.

**Comment by theidentity** [comment]
@gden138 

Just ran the code and didn't encounter the issue. If you are running on a different dataset, could you check if the `num_classes` is updated. That might sometimes cause this problem. 

These are the logs that I am getting 

- CIFAR10

```
Epoch 0 disc_loss 1.415 gen_loss 4.547 val_loss 2.289 acc 0.127                                                                                                                                                    
Best model updated - Loss reduced to : 2.2892613101005552
```

- MNIST

```
Epoch 0 disc_loss 1.158 gen_loss 3.352 val_loss 1.048 acc 0.664
Best model updated - Loss reduced to : 1.047597603003184

```
